INFO 2022-09-28 22:46:34,014 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:49:07,497 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:50:07,578 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\dev.py changed, reloading.
INFO 2022-09-28 22:50:08,565 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:50:12,834 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:50:56,467 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\__init__.py changed, reloading.
INFO 2022-09-28 22:50:57,697 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:51:29,193 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\dev.py changed, reloading.
INFO 2022-09-28 22:51:31,385 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:52:12,137 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:52:31,128 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:54:18,089 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:54:34,354 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\urls.py changed, reloading.
INFO 2022-09-28 22:54:35,792 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:56:31,674 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:57:26,500 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\dev.py changed, reloading.
INFO 2022-09-28 22:57:27,937 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:57:43,146 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\dev.py changed, reloading.
INFO 2022-09-28 22:57:44,588 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:57:48,310 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 22:58:05,829 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\dev.py changed, reloading.
INFO 2022-09-28 22:58:07,247 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:05:25,994 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\__init__.py changed, reloading.
INFO 2022-09-28 23:05:27,347 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:05:36,435 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\__init__.py changed, reloading.
INFO 2022-09-28 23:05:37,893 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:06:31,573 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\urls.py changed, reloading.
INFO 2022-09-28 23:06:33,011 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:07:00,126 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\dev.py changed, reloading.
INFO 2022-09-28 23:07:01,663 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:09:18,459 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:15:10,304 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\dev.py changed, reloading.
INFO 2022-09-28 23:15:12,089 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:15:19,160 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:22:47,295 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\dev.py changed, reloading.
INFO 2022-09-28 23:22:48,774 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:22:54,263 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\dev.py changed, reloading.
INFO 2022-09-28 23:22:55,741 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:23:30,209 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\dev.py changed, reloading.
INFO 2022-09-28 23:23:31,813 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:24:08,590 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\settings\dev.py changed, reloading.
INFO 2022-09-28 23:24:10,309 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:24:54,465 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\urls.py changed, reloading.
INFO 2022-09-28 23:24:55,914 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:25:19,599 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\urls.py changed, reloading.
INFO 2022-09-28 23:25:21,065 autoreload 597 Watching for file changes with StatReloader
INFO 2022-09-28 23:25:53,585 autoreload 597 Watching for file changes with StatReloader
WARNING 2022-09-28 23:26:17,296 base 114 Session data corrupted
INFO 2022-09-28 23:26:17,353 basehttp 154 "GET /xadmin/ HTTP/1.1" 200 4241
INFO 2022-09-28 23:26:17,469 basehttp 154 "GET /static/static/xadmin/css/themes/bootstrap-xadmin.css HTTP/1.1" 200 1888
INFO 2022-09-28 23:26:17,469 basehttp 154 "GET /static/static/xadmin/css/xadmin.plugins.css HTTP/1.1" 200 175
INFO 2022-09-28 23:26:17,470 basehttp 154 "GET /static/static/xadmin/css/xadmin.main.css HTTP/1.1" 200 8376
INFO 2022-09-28 23:26:17,471 basehttp 154 "GET /static/static/xadmin/vendor/font-awesome/css/font-awesome.css HTTP/1.1" 200 21658
INFO 2022-09-28 23:26:17,471 basehttp 154 "GET /static/static/xadmin/css/xadmin.responsive.css HTTP/1.1" 200 4361
INFO 2022-09-28 23:26:17,472 basehttp 154 "GET /static/static/xadmin/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 126432
INFO 2022-09-28 23:26:17,483 basehttp 154 "GET /static/static/xadmin/vendor/jquery-ui/jquery.ui.widget.js HTTP/1.1" 200 15069
INFO 2022-09-28 23:26:17,484 basehttp 154 "GET /static/static/xadmin/vendor/jquery-ui/jquery.ui.core.js HTTP/1.1" 200 8195
INFO 2022-09-28 23:26:17,484 basehttp 154 "GET /static/static/xadmin/vendor/jquery-ui/jquery.ui.mouse.js HTTP/1.1" 200 4561
INFO 2022-09-28 23:26:17,485 basehttp 154 "GET /static/static/xadmin/vendor/jquery-ui/jquery.ui.sortable.js HTTP/1.1" 200 42543
WARNING 2022-09-28 23:26:17,486 base 114 Session data corrupted
INFO 2022-09-28 23:26:17,489 basehttp 154 "GET /static/static/xadmin/vendor/jquery/jquery.js HTTP/1.1" 200 240196
INFO 2022-09-28 23:26:17,503 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 200 4248
INFO 2022-09-28 23:26:17,505 basehttp 154 "GET /static/static/xadmin/js/xadmin.main.js HTTP/1.1" 200 3401
INFO 2022-09-28 23:26:17,505 basehttp 154 "GET /static/static/xadmin/vendor/bootstrap/js/bootstrap.js HTTP/1.1" 200 58327
INFO 2022-09-28 23:26:17,506 basehttp 154 "GET /static/static/xadmin/js/xadmin.responsive.js HTTP/1.1" 200 4165
INFO 2022-09-28 23:26:17,556 basehttp 154 "GET /static/static/xadmin/vendor/font-awesome/fonts/fontawesome-webfont.woff?v=4.0.3 HTTP/1.1" 200 44432
INFO 2022-09-28 23:26:28,530 autoreload 597 Watching for file changes with StatReloader
WARNING 2022-09-28 23:26:30,193 log 222 Not Found: /
WARNING 2022-09-28 23:26:30,194 basehttp 154 "GET / HTTP/1.1" 404 2077
WARNING 2022-09-28 23:26:35,776 base 114 Session data corrupted
INFO 2022-09-28 23:26:35,802 basehttp 154 "GET /xadmin/ HTTP/1.1" 200 4241
WARNING 2022-09-28 23:26:35,888 base 114 Session data corrupted
INFO 2022-09-28 23:26:35,898 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 200 4248
WARNING 2022-09-28 23:26:39,813 base 114 Session data corrupted
ERROR 2022-09-28 23:26:43,154 log 222 Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'luffy.auth_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\extra_apps\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\extra_apps\xadmin\sites.py", line 207, in inner
    return self.create_admin_view(self.login_view)(request, *args, **kwargs)
  File "D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\extra_apps\xadmin\views\base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\extra_apps\xadmin\views\website.py", line 71, in post
    return self.get(request)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\extra_apps\xadmin\views\website.py", line 67, in get
    return login.as_view(**defaults)(request)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\decorators\debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\views.py", line 61, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\edit.py", line 141, in post
    if form.is_valid():
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\forms\forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\forms\forms.py", line 180, in errors
    self.full_clean()
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\forms\forms.py", line 382, in full_clean
    self._clean_form()
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\forms\forms.py", line 409, in _clean_form
    cleaned_data = self.clean()
  File "D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\extra_apps\xadmin\forms.py", line 29, in clean
    self.user_cache = authenticate(
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\backends.py", line 20, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\base_user.py", line 44, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 402, in get
    num = len(clone)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 256, in __len__
    self._fetch_all()
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\wh\AppData\Local\Programs\Python\Python39\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'luffy.auth_user' doesn't exist")
ERROR 2022-09-28 23:26:43,163 basehttp 154 "POST /xadmin/ HTTP/1.1" 500 325697
WARNING 2022-09-28 23:26:44,952 base 114 Session data corrupted
INFO 2022-09-28 23:26:44,960 basehttp 154 "GET /xadmin/ HTTP/1.1" 200 4241
WARNING 2022-09-28 23:26:45,043 base 114 Session data corrupted
INFO 2022-09-28 23:26:45,051 basehttp 154 "GET /xadmin/jsi18n/ HTTP/1.1" 200 4248
INFO 2022-09-28 23:27:11,954 autoreload 217 D:\PycharmProjects\gx\djangoProject\ai_detection_backend\ai_detection_backend\urls.py changed, reloading.
INFO 2022-09-28 23:27:13,358 autoreload 597 Watching for file changes with StatReloader
